name: ☑️ Code Check

on: [push]

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit
      run: pip install pre-commit poetry pytest typing-extensions
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Install dependencies
      run: poetry config virtualenvs.create false && poetry install --extras "all"
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: pytest
