name: ☑️ Code Check

on: [push]

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry and dependencies
      run: curl -sSL https://install.python-poetry.org | python3 - && poetry install
    - name: Run pre-commit
      run: poetry run pre-commit run --all-files
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: poetry run pytest
