name: ☑️ Code Check

on: [push]

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install rye and dependencies
      uses: eifinger/setup-rye@v1
    - name: Sync rye
      run: rye sync
    - name: Run pre-commit
      run: rye run pre-commit run --all-files
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: rye run pytest
